/*
 * generated by Xtext 2.9.2
 */
package org.eclipse.ice.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.ice.example.parser.antlr.internal.InternalExampleParser;
import org.eclipse.ice.example.services.ExampleGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ExampleParser extends AbstractAntlrParser {

	@Inject
	private ExampleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_COMMENT", "RULE_WHITESPACE");
	}
	

	@Override
	protected InternalExampleParser createParser(XtextTokenStream stream) {
		return new InternalExampleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Input";
	}

	public ExampleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExampleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
