/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.ini.ui.internal.IniActivator;

public class InputUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IniActivator.getInstance().getInjector("org.eclipse.ice.project.Input");
	}

}
