/*
 * generated by Xtext 2.9.2
 */
package org.eclipse.ice.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExampleScopeProvider extends DelegatingScopeProvider {
}
