/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.example.scoping;

import org.eclipse.ice.example.scoping.AbstractExampleScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ExampleScopeProvider extends AbstractExampleScopeProvider {
}
