/*******************************************************************************
 * Copyright (c) 2014 UT-Battelle, LLC.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Initial API and implementation and/or initial documentation - Jay Jay Billings,
 *   Jordan H. Deyton, Dasha Gorin, Alexander J. McCaskey, Taylor Patterson,
 *   Claire Saunders, Matthew Wang, Anna Wojtowicz
 *******************************************************************************/
package org.eclipse.ice.example.io;

import org.eclipse.ice.io.serializable.IWriter;
import org.eclipse.core.resources.IFile;
import org.eclipse.ice.datastructures.form.Form;

/**
 * Writer service for Xtext generated language infrastructure.
 * This class was generated by the Eclipse ICE Parser Generator
 * Item.
 */
class ExampleWriter implements IWriter {

	/**
	 * Constructor
	 */
	public ExampleWriter() {
		super();
	}

	/**
	 * Write a form out to a file stipulated by the 
	 * Xtext generated grammar infrastructure.
	 */
	@Override
	public void write(Form formToWrite, IFile file) {
		// TODO Auto-generated method stub
		
	}

	/**
	 * Search through the given file and replace any 
	 * occurrences that match the given regex with 
	 * the given value
	 */
	@Override
	public void replace(IFile file, String regex, String value) {
		// TODO Auto-generated method stub
		
	}

	/**
	 * Tell us what type of writer this is.
	 */
	@Override
	public String getWriterType() {
		// TODO Auto-generated method stub
		return "Example Writer";
	}
}
