/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class InputRuntimeModule extends AbstractInputRuntimeModule {
}
