/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class InputStandaloneSetup extends InputStandaloneSetupGenerated {

	def static void doSetup() {
		new InputStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
