/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractInputScopeProvider extends DelegatingScopeProvider {
}
