/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.ice.project.parser.antlr.internal.InternalInputParser;
import org.eclipse.ice.project.services.InputGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class InputParser extends AbstractAntlrParser {

	@Inject
	private InputGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_COMMENT", "RULE_WHITESPACE");
	}
	

	@Override
	protected InternalInputParser createParser(XtextTokenStream stream) {
		return new InternalInputParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Input";
	}

	public InputGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InputGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
