/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.example;

import org.eclipse.ice.example.ExampleStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExampleStandaloneSetup extends ExampleStandaloneSetupGenerated {
  public static void doSetup() {
    ExampleStandaloneSetup _exampleStandaloneSetup = new ExampleStandaloneSetup();
    _exampleStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
