/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.example;

import org.eclipse.ice.example.AbstractExampleRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExampleRuntimeModule extends AbstractExampleRuntimeModule {
}
