/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project.tests

import com.google.inject.Inject
import org.eclipse.ice.project.project.Input
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(InputInjectorProvider)
class InputParsingTest{

	@Inject
	ParseHelper<Input> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
