/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.ice.project.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class InputGrammarAccess extends AbstractGrammarElementFinder {
	
	public class InputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.Input");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInputAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cNEWLINETerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cSectionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSectionsSectionParserRuleCall_2_0 = (RuleCall)cSectionsAssignment_2.eContents().get(0);
		
		//Input:
		//	{Input} NEWLINE*
		//	sections+=Section*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Input} NEWLINE* sections+=Section*
		public Group getGroup() { return cGroup; }
		
		//{Input}
		public Action getInputAction_0() { return cInputAction_0; }
		
		//NEWLINE*
		public RuleCall getNEWLINETerminalRuleCall_1() { return cNEWLINETerminalRuleCall_1; }
		
		//sections+=Section*
		public Assignment getSectionsAssignment_2() { return cSectionsAssignment_2; }
		
		//Section
		public RuleCall getSectionsSectionParserRuleCall_2_0() { return cSectionsSectionParserRuleCall_2_0; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOPENTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cCLOSETerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cNEWLINETerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cLinesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLinesLineParserRuleCall_3_1_0 = (RuleCall)cLinesAssignment_3_1.eContents().get(0);
		private final RuleCall cNEWLINETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//Section:
		//	OPEN name=ID CLOSE (NEWLINE* lines+=Line)*
		//	NEWLINE*;
		@Override public ParserRule getRule() { return rule; }
		
		//OPEN name=ID CLOSE (NEWLINE* lines+=Line)* NEWLINE*
		public Group getGroup() { return cGroup; }
		
		//OPEN
		public RuleCall getOPENTerminalRuleCall_0() { return cOPENTerminalRuleCall_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//CLOSE
		public RuleCall getCLOSETerminalRuleCall_2() { return cCLOSETerminalRuleCall_2; }
		
		//(NEWLINE* lines+=Line)*
		public Group getGroup_3() { return cGroup_3; }
		
		//NEWLINE*
		public RuleCall getNEWLINETerminalRuleCall_3_0() { return cNEWLINETerminalRuleCall_3_0; }
		
		//lines+=Line
		public Assignment getLinesAssignment_3_1() { return cLinesAssignment_3_1; }
		
		//Line
		public RuleCall getLinesLineParserRuleCall_3_1_0() { return cLinesLineParserRuleCall_3_1_0; }
		
		//NEWLINE*
		public RuleCall getNEWLINETerminalRuleCall_4() { return cNEWLINETerminalRuleCall_4; }
	}
	public class LineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.Line");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWHITESPACETerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cASSIGNTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueIDTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//Line:
		//	WHITESPACE? name=ID ASSIGN value=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//WHITESPACE? name=ID ASSIGN value=ID
		public Group getGroup() { return cGroup; }
		
		//WHITESPACE?
		public RuleCall getWHITESPACETerminalRuleCall_0() { return cWHITESPACETerminalRuleCall_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//ASSIGN
		public RuleCall getASSIGNTerminalRuleCall_2() { return cASSIGNTerminalRuleCall_2; }
		
		//value=ID
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_3_0() { return cValueIDTerminalRuleCall_3_0; }
	}
	
	
	private final InputElements pInput;
	private final SectionElements pSection;
	private final LineElements pLine;
	private final TerminalRule tWHITESPACE;
	private final TerminalRule tNEWLINE;
	private final TerminalRule tID;
	private final TerminalRule tCOMMENT;
	private final TerminalRule tOPEN;
	private final TerminalRule tCLOSE;
	private final TerminalRule tASSIGN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public InputGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pInput = new InputElements();
		this.pSection = new SectionElements();
		this.pLine = new LineElements();
		this.tWHITESPACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.WHITESPACE");
		this.tNEWLINE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.NEWLINE");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.ID");
		this.tCOMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.COMMENT");
		this.tOPEN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.OPEN");
		this.tCLOSE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.CLOSE");
		this.tASSIGN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.ice.project.Input.ASSIGN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.ice.project.Input".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Input:
	//	{Input} NEWLINE*
	//	sections+=Section*;
	public InputElements getInputAccess() {
		return pInput;
	}
	
	public ParserRule getInputRule() {
		return getInputAccess().getRule();
	}
	
	//Section:
	//	OPEN name=ID CLOSE (NEWLINE* lines+=Line)*
	//	NEWLINE*;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//Line:
	//	WHITESPACE? name=ID ASSIGN value=ID;
	public LineElements getLineAccess() {
		return pLine;
	}
	
	public ParserRule getLineRule() {
		return getLineAccess().getRule();
	}
	
	//terminal WHITESPACE:
	//	' ' | '\t'+;
	public TerminalRule getWHITESPACERule() {
		return tWHITESPACE;
	}
	
	//terminal NEWLINE:
	//	'\r'? '\n'+;
	public TerminalRule getNEWLINERule() {
		return tNEWLINE;
	}
	
	//terminal ID:
	//	('A'..'Z' | 'a'..'z') ('A'..'Z' | 'a'..'z' | '_' | '-' | '\\' | '/' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal COMMENT:
	//	'#' !('\n' | '\r')*;
	public TerminalRule getCOMMENTRule() {
		return tCOMMENT;
	}
	
	//terminal OPEN:
	//	'[';
	public TerminalRule getOPENRule() {
		return tOPEN;
	}
	
	//terminal CLOSE:
	//	']';
	public TerminalRule getCLOSERule() {
		return tCLOSE;
	}
	
	//terminal ASSIGN:
	//	'=';
	public TerminalRule getASSIGNRule() {
		return tASSIGN;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
